### ISSUE TITLE
Issue authenticating using e-mail

### ISSUE THREAD

**Issue by kernsb** [biblibre/omeka-s-module-Ldap#3]
While I have this configured and working for usernames, I am having trouble getting any authentication via e-mail address instead of username. Currently when someone logs in, a user is created as DOMAIN\user. However, the previous LDAP plugin by digihum created users as username@domain.com, and I need these accounts that already exist to continue working as they already own assets, and have correct access. Any ideas?

If this is not possible, could an option be added to parse the username off of the beginning when an '@' is detected and use it for authentication, but record and use the user in the email format to line up with the previous plug-in? Sort of a 'compatibility mode', so to speak?

**Comment by kernsb** [comment]
Any movement on this? Even a reply? Has development on this plugin ceased?

**Comment by jajm** [comment]
This activity on this module is indeed low, because it already does everything we need (for now).
However we accept pull requests if you are willing to work on this.

About the feature you are requesting, I'm not sure to understand what you want exactly. Can't users just enter their credentials without the '@domain.com' part ? The email address can be retrieved from LDAP (if the "email attribute" setting is correctly set) and the module will find the Omeka user account matching that email address. Have you tried that ?

**Comment by kernsb** [comment]
You are correct, apparently the issue was with the email mapping not working properly. I had set the field to use to 'userPrincipalName', which does contain the needed email value, but it was not working. After setting the field to 'mail' instead (which also held the same value) it is functioning properly. So I feel dumb, but I guess the moral of the story is that it doesn't like 'userPrincipalName' for some reason. Consider this closed.
